title: My Jekyll Website
description: This is a simple website built with Jekyll and hosted on GitHub Pages.
baseurl: ""
url: "https://yourusername.github.io/my-jekyll-website"
theme: minima
markdown: kramdown
permalink: pretty
plugins:
  - jekyll-feed
  - jekyll-seo-tag
exclude:
  - Gemfile
  - Gemfile.lock
  - README.md
  - _config.yml
  - _posts
  - _layouts
  - _includes
  - _sass
  - assets